export const CONSTRUCTOR_ADD_INGREDIENT = "CONSTRUCTOR_ADD_INGREDIENT";
export const CONSTRUCTOR_DELETE_INGREDIENT = "CONSTRUCTOR_DELETE_INGREDIENT";
export const CONSTRUCTOR_MOVE_INGREDIENT = "CONSTRUCTOR_MOVE_INGREDIENT";
export const CONSTRUCTOR_RESET_INGREDIENT = "CONSTRUCTOR_RESET_INGREDIENT";